# Generated by Django 3.0.5 on 2020-04-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=1, upload_to='users/%Y/%m'),
            preserve_default=False,
        ),
    ]
