# Generated by Django 3.0.3 on 2020-04-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cover',
            field=models.ImageField(null=True, upload_to='cover/%Y/%m'),
        ),
    ]
