# Generated by Django 3.0.3 on 2020-04-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_review_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
    ]
