# Generated by Django 3.0.3 on 2020-04-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200415_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreviews',
            old_name='song',
            new_name='review',
        ),
    ]
