# Generated by Django 3.0.3 on 2020-04-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20200415_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
