# Generated by Django 3.0.3 on 2020-04-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
